from __future__ import annotations

INDEX_SYMBOLS = {
    "nifty": "^NSEI",
    "bank_nifty": "^NSEBANK",
    "india_vix": "^INDIAVIX",
}

SECTOR_INDICES = [
    ("Nifty IT", "^CNXIT"),
    ("Nifty Auto", "^CNXAUTO"),
    ("Nifty Pharma", "^CNXPHARMA"),
    ("Nifty FMCG", "^CNXFMCG"),
    ("Nifty Metal", "^CNXMETAL"),
    ("Nifty Realty", "^CNXREALTY"),
    ("Nifty Energy", "^CNXENERGY"),
    ("Nifty Financial Services", "NIFTY_FIN_SERVICE.NS"),
]

STOCK_UNIVERSE = [
    ("RELIANCE.NS", "Reliance Industries", "Nifty Energy"),
    ("ONGC.NS", "ONGC", "Nifty Energy"),
    ("POWERGRID.NS", "Power Grid", "Nifty Energy"),
    ("NTPC.NS", "NTPC", "Nifty Energy"),
    ("TCS.NS", "Tata Consultancy Services", "Nifty IT"),
    ("INFY.NS", "Infosys", "Nifty IT"),
    ("HCLTECH.NS", "HCLTech", "Nifty IT"),
    ("WIPRO.NS", "Wipro", "Nifty IT"),
    ("TECHM.NS", "Tech Mahindra", "Nifty IT"),
    ("HDFCBANK.NS", "HDFC Bank", "Nifty Financial Services"),
    ("ICICIBANK.NS", "ICICI Bank", "Nifty Financial Services"),
    ("SBIN.NS", "State Bank of India", "Nifty Financial Services"),
    ("AXISBANK.NS", "Axis Bank", "Nifty Financial Services"),
    ("KOTAKBANK.NS", "Kotak Mahindra Bank", "Nifty Financial Services"),
    ("BAJFINANCE.NS", "Bajaj Finance", "Nifty Financial Services"),
    ("TVSMOTOR.NS", "TVS Motor", "Nifty Auto"),
    ("MARUTI.NS", "Maruti Suzuki", "Nifty Auto"),
    ("M&M.NS", "Mahindra & Mahindra", "Nifty Auto"),
    ("EICHERMOT.NS", "Eicher Motors", "Nifty Auto"),
    ("BAJAJ-AUTO.NS", "Bajaj Auto", "Nifty Auto"),
    ("SUNPHARMA.NS", "Sun Pharma", "Nifty Pharma"),
    ("CIPLA.NS", "Cipla", "Nifty Pharma"),
    ("DRREDDY.NS", "Dr. Reddy's Laboratories", "Nifty Pharma"),
    ("DIVISLAB.NS", "Divi's Laboratories", "Nifty Pharma"),
    ("ITC.NS", "ITC", "Nifty FMCG"),
    ("HINDUNILVR.NS", "Hindustan Unilever", "Nifty FMCG"),
    ("NESTLEIND.NS", "Nestle India", "Nifty FMCG"),
    ("BRITANNIA.NS", "Britannia", "Nifty FMCG"),
    ("TATASTEEL.NS", "Tata Steel", "Nifty Metal"),
    ("JSWSTEEL.NS", "JSW Steel", "Nifty Metal"),
    ("HINDALCO.NS", "Hindalco", "Nifty Metal"),
    ("COALINDIA.NS", "Coal India", "Nifty Metal"),
    ("DLF.NS", "DLF", "Nifty Realty"),
    ("GODREJPROP.NS", "Godrej Properties", "Nifty Realty"),
    ("OBEROIRLTY.NS", "Oberoi Realty", "Nifty Realty"),
    ("PRESTIGE.NS", "Prestige Estates", "Nifty Realty"),
    ("LT.NS", "Larsen & Toubro", "Infrastructure"),
    ("BHARTIARTL.NS", "Bharti Airtel", "Telecom"),
    ("ADANIENT.NS", "Adani Enterprises", "Diversified"),
    ("TITAN.NS", "Titan", "Consumer"),
]
